config/routes.rb
Rails.application.routes.draw do
  devise_for :admin
  resources :categories
  get '/orders/new_order', to: 'orders#new', as: 'orders_new'
  resources :orders
  namespace :admins do
    resources :products
    namespace :products do
      delete 'remove_cover_image'
      post 'csv_upload'
    end
  end
  root to: 'admins/products#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_product.rb
class CategoriesProduct < ApplicationRecord
    belongs_to :category
    belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :categories_products
    has_many :products, through: :categories_products
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    enum status: [:draft, :published, :archived]
    validates :stock, numericality: {greater_than_or_equal_to: 0}
    validates :title, length: {minimum: 1 }
    validates :description, length: {minimum: 1}

    has_many :categories_products
    has_many :categories, through: :categories_products

    has_one_attached :cover_image
    has_many_attached :images

    attr_accessor :remove_cover_image, :remove_images
    after_save :purge_cover_image, if: :remove_cover_image
    private def purge_cover_image
        return unless @remove_cover_image == '1'
        cover_image.purge_later
    end

    after_save :purge_images, if: :remove_images
    private def purge_images
        return unless @remove_images == '1'
        images.purge_later
    end
end

app/controllers/admins/products_controller.rb
module Admins
  class ProductsController < ApplicationController
    before_action :authenticate_admin!, except: [:index, :show]
    before_action :set_product, only: %i[ show edit update destroy ]

    def index
      @search = params[:search]
      @products = Product.all
      @products = @products.where("title LIKE ? or description LIKE ?" , "%#{@search}%", "%#{@search}%") if @search.present?
      @products = @products.page(params[:page]).per(5)
      respond_to do |format|
        format.html
        format.csv { send_data generate_csv(Product.all), file_name: 'products.csv' }
      end
    end

    def show
      @product = Product.find(params[:id])
    end

    def new
      puts "This is how you print out something."
      @product = Product.new
    end

    def edit
      @product = Product.find(params[:id])
    end

    def create
      @product = Product.create(product_params)

      if @product.invalid?
        flash[:error] = @product.errors.full_messages
      end

      redirect_to action: :index
    end

    def update
      @product = Product.find(params[:id])
      @product.update(product_params)
      redirect_to action: :index
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to action: :index
    end


    def csv_upload
      data = params[:csv_file].read.split("\n")
      data.each do |line|
        attr = line.split(",").map(&:strip)
        Product.create title: attr[0], description: attr[1], stock: attr[2]
      end
      redirect_to action: :index
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def generate_csv(products)
      products.map { |a| [a.title, a.description, a.stock , a.created_at.to_date].join(',') }.join("\n")
    end

    def product_params
      params.require(:product).permit(:title, :status, :description, :stock, :cover_image, :primary_image, :remove_cover_image, :remove_images, category_ids: [], images: [])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_admin!, only: [:index]

    def index
        @orders = Order.all
    end

    def show
        @order = Order.find(params[:id])
        @product = Product.find(@order.product_id)
    end
    
    def new
        @order = Order.new
        @product = Product.find(params[:id].to_i)
        @product_id = params[:id].to_i
    end

    def create
        @order = Order.new(order_params)

        if @order.save
            redirect_to @order
        else
            render :new
        end
    end

    private
        def order_params
            params.require(:order).permit(:product_id, :address)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/products/_form.slim
= form_with(model: [:admins, product]) do |f|
    = f.label :title
    = f.text_field :title, placeholder: 'Title'
    br
    = f.label :description
    = f.text_area :description, placeholder: 'Write description here'
    br
    = f.label :stock
    = f.text_field :stock, data: { numeric: true } 
    br
    = f.label :cover_image
    = f.file_field :cover_image
    - if product.cover_image.attached?
        br 
        = image_tag product.cover_image, width: '64px'
        br
        = f.label :remove_cover_image
        = f.check_box(:remove_cover_image)
    br
    = f.label :images
    = f.file_field :images, multiple: true
    br
    - if product.images.attached?
        br
        - product.images.each do |image|
            = image_tag image, width: '64px'
        br
        = f.label :remove_images
        = f.check_box(:remove_images)
    br
    = f.label :categories
    = f.collection_select :category_ids, Category.order(:name), :id, :name, {}, multiple: true
    br
    = f.label :status
    = f.select :status, Product.statuses.keys.map {|u| [u.titleize, u]}
    br
    = f.submit 'Submit stock'

app/views/admins/products/edit.slim
h1 Edit stock

div = link_to admins_products_path do
        = button_tag 'Back', class: 'btn btn-primary'

br
= render 'form', product: @product

app/views/admins/products/index.slim
.container
    .row
        .col-6  
            h1 List of stock
        .col-6
            .float-right
                span = link_to "Product", admins_products_path,class:"nav-link"
                span = link_to "Catagory", categories_path, class:"nav-link"
                - if admin_signed_in?
                    span = link_to "Order", orders_path, class:"nav-link"
                    span = current_admin.email
                    span.ml-3 = link_to 'Logout', destroy_admin_session_path,  method: :delete 
                - else
                    = link_to admin_session_path do
                        = button_tag 'Login', class: 'btn btn-primary'


    .row
        .col
            = form_tag root_path, method: :get do
                = text_field_tag 'search', '', placeholder: 'Type something here',
                    class: 'form-control'
        .col-2
            = link_to admins_products_path(format: :csv) do
                = button_tag 'Download CSV', class: 'btn btn-secondary float-right'
    br
    .row-mt-2
        .col
            table.table.table-bordered.table-striped
                thead.thead-dark
                    tr
                        th Cover image
                        th Title
                        th Status
                        th Category
                        th Description
                        th Stock
                        th images
                        th Created at
                        th Updated at
                        th Action
                tbody
                    - @products.each do |a|
                     tr
                        td
                            - if a.cover_image.attached?
                                = image_tag a.cover_image, width: '64px'
                        td.font-weight-bold = a.title
                        td.font-weight-light = a.status
                        td 
                            - a.categories.each do |category|
                                = link_to category do 
                                    = category.name
                        td = a.description
                        td = a.stock
                        td  
                            -  a.images.each do |image|
                                = image_tag image, width: '32px'
                        td.font-weight-light = "#{time_ago_in_words(a.created_at.to_date)} Ago"
                        td.font-weight-light = "#{time_ago_in_words(a.updated_at.to_date)} Ago"
                        td
                            span.ml-3
                                = link_to admins_product_path(a) do
                                    i.fas.fa-eye
                            - if admin_signed_in?
                                span.ml-3
                                    = link_to edit_admins_product_path(a) do
                                        i.fas.fa-pen
                                span.ml-3
                                    = link_to admins_product_path(a), method: :delete do
                                        i.fas.fa-trash
                            span.ml-3
                                = link_to new_order_path(:id => a.id) do
                                    i.fas.fa-shopping-cart

.row
    .col-6
        = paginate @products
    - if admin_signed_in?
        .col
            .float-right
                = link_to new_admins_product_path do
                    = button_tag 'Add new item', class: 'btn btn-primary'

        .col
            = form_tag admins_products_csv_upload_path, multipart: true do
                div = file_field_tag :csv_file
                div = submit_tag :upload

app/views/admins/products/new.slim
h1 Add new stock

div = link_to admins_products_path do
        = button_tag 'Back', class: 'btn btn-primary'
br
= render 'form', product: @product

app/views/admins/products/show.slim
h1 = @product.title
.form-control
   strong Description
   br
   = @product.description
   br
   strong Stock : 
   = @product.stock 
   br
   strong Category
   br
   li.category-link
      - @product.categories.each do |category|
         = link_to category do 
            = category.name
   br
   strong Cover image
   br
      - if @product.cover_image.attached?
         = image_tag @product.cover_image, width: '64px'
   br
   strong Images
   br
   - if @product.images.attached?
      - @product.images.each do |image|
         = image_tag image, width: '32px'
   br
br
div = link_to admins_products_path do
      = button_tag 'Back', class: 'btn btn-primary'

app/views/categories/_category.html.erb
<li class="category-link">
    <%= link_to category_path(category) do %>
        <%= category.name %>
    <% end %>
</li>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.slim
h1 Categories
.container
    = render @categories
    = link_to 'New Category', new_category_path, class: 'btn btn-primary'
= link_to admins_products_path do
    = button_tag 'Back', class: 'btn btn-primary'

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1>
  <%= @category.name %>
</h1>

<div class="container">
  <% @category.products.each do |product| %>
      <h3><%= product.title %></h3>
      <%= link_to 'Info', admins_product_path(product), class:"btn btn-primary" %>
      <% if admin_signed_in? %>
          <%= link_to 'Edit', edit_admins_product_path(product), class:"btn btn-secondary" %>
          <%= link_to 'Delete', admins_product_path(product), method: :delete, data: { confirm:"Are you sure?"}, class:"btn btn-danger"%>
      <% end %>
  <% end %>
</div>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/commerces/edit.slim
h1 Edit stock

div = link_to commerces_path do
        = button_tag 'Back', class: 'btn btn-primary'

br
= render 'form', commerce: @commerce

app/views/commerces/index.slim
- if signed_in?
    .container
        .row
            .col-6  
                h1 List of stock
            .col-6
                .float-right
                    span = current_admin.email
                    / span.ml-3 = "#{current_admin.firstname} #{current_admin.lastname}"
                    span.ml-3 = link_to 'Logout', destroy_admin_session_path,  method: :delete 

        .row
            .col
                = form_tag commerces_path, method: :get do
                    = text_field_tag 'search', '', placeholder: 'Type something here',
                        class: 'form-control'
        br
        .row-mt-2
            .col
                table.table.table-bordered.table-striped
                    thead.thead-dark
                        tr
                            th ID
                            th Title
                            th Description
                            th Stock
                            th Created at
                            th Updated at
                            th Action
                    tbody
                      - @commerces.each do |a|
                        tr
                            td = a.id
                            td.font-weight-bold = a.title
                            td = a.description
                            td = a.stock
                            td.font-weight-light = "#{time_ago_in_words(a.created_at.to_date)} Ago"
                            td.font-weight-light = "#{time_ago_in_words(a.updated_at.to_date)} Ago"
                        td
                            span.mr-3
                                = link_to commerce_path(a) do
                                    i.fas.fa-eye
                            span.mr-2
                                = link_to edit_commerce_path(a) do
                                    i.fas.fa-pen
                            span.mr-2
                                = link_to commerce_path(a), method: :delete do
                                    i.fas.fa-trash

    .row
        .col-6
            = paginate @commerces
        .col
            .float-right
                = link_to new_commerce_path do
                    = button_tag 'Add new item', class: 'btn btn-primary'

- else
    .container
        .row
            .col-6  
                .float-right
                    = link_to admin_session_path do
                        = button_tag 'Login', class: 'btn btn-primary'
                h1 List of stock
                
        .row
            .col
                = form_tag commerces_path, method: :get do
                    = text_field_tag 'search', '', placeholder: 'Type something here',
                        class: 'form-control'
        br
        .row-mt-2
            .col
                table.table.table-bordered.table-striped
                    thead.thead-dark
                        tr
                            th ID
                            th Title
                            th Description
                            th Stock
                    tbody
                      - @commerces.each do |a|
                        tr
                            td = a.id
                            td.font-weight-bold = a.title
                            td = a.description
                            td = a.stock

        .row
            .col-6
                = paginate @commerces

app/views/commerces/new.slim
h1 Add new stock

div = link_to commerces_path do
        = button_tag 'Back', class: 'btn btn-primary'
br
= render 'form', commerce: @commerce

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ssd20216210546382Commerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.slim.min.js'%>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js'%>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'%>
  </body>
</html>

app/views/orders/index.slim
.container
    .row
        .col-6  
            h1 Order list
        .col-6
            .float-right
                span = link_to "Product", admins_products_path,class:"nav-link"
                span = link_to "Catagory", categories_path, class:"nav-link"
                - if admin_signed_in?
                    span = link_to "Order", orders_path, class:"nav-link"
                    span = current_admin.email
                    span.ml-3 = link_to 'Logout', destroy_admin_session_path,  method: :delete 
                - else
                    = link_to admin_session_path do
                        = button_tag 'Login', class: 'btn btn-primary'

- @orders.each do |order|
    .col-3
        - if Product.find(order.product_id).cover_image.attached?
            = image_tag  Product.find(order.product_id).cover_image, width: '100%'
    .col-9
        .row
            .col
                h1 =  Product.find(order.product_id).title
          
                .col
                  =  "address: #{order.address}"

app/views/orders/new.slim
h1 Add new order

= form_with(model: @order) do |f|
    = f.hidden_field :product_id, value: @product_id
    = f.label :address
    br
    = f.text_area :address
    br
    = f.submit
div = link_to root_path do
        = button_tag 'Back', class: 'btn btn-primary'

app/views/orders/show.slim
h1 = @product.title
- if @product.cover_image.attached?
    = image_tag @product.cover_image, width: '100%'
h3 = "Address: #{@order.address}"

= link_to root_path do 
    = button_tag 'Back', class: 'btn btn-primary'

app/views/products/edit.slim
h1 Edit stock

div = link_to products_path do
        = button_tag 'Back', class: 'btn btn-primary'

br
= render 'form', product: @product

app/views/products/index.slim
- if signed_in?
    .container
        .row
            .col-6  
                h1 List of stock
            .col-6
                .float-right
                    span = current_admin.email
                    span = link_to "Catagory", categories_path, class:"nav-link"
                    span.ml-3 = link_to 'Logout', destroy_admin_session_path,  method: :delete 

        .row
            .col
                = form_tag products_path, method: :get do
                    = text_field_tag 'search', '', placeholder: 'Type something here',
                        class: 'form-control'
            .col-2
                = link_to products_path(format: :csv) do
                    = button_tag 'Download CSV', class: 'btn btn-secondary float-right'
        br
        .row-mt-2
            .col
                table.table.table-bordered.table-striped
                    thead.thead-dark
                        tr
                            th Title
                            th Status
                            th Description
                            th Stock
                            th Category
                            th Created at
                            th Updated at
                            th Action
                    tbody
                      - @products.each do |a|
                        tr
                            td.font-weight-bold = a.title
                            td.font-weight-light = a.status
                            td = a.description
                            td = a.stock
                            td = render a.categories
                            td.font-weight-light = "#{time_ago_in_words(a.created_at.to_date)} Ago"
                            td.font-weight-light = "#{time_ago_in_words(a.updated_at.to_date)} Ago"
                            td
                                span.mr-3
                                    = link_to product_path(a) do
                                        i.fas.fa-eye
                                span.mr-2
                                    = link_to edit_product_path(a) do
                                        i.fas.fa-pen
                                span.mr-2
                                    = link_to product_path(a), method: :delete do
                                        i.fas.fa-trash

    .row
        .col-6
            = paginate @products
        .col
            .float-right
                = link_to new_product_path do
                    = button_tag 'Add new item', class: 'btn btn-primary'
    .row
        .col
            = form_tag products_csv_upload_path, multipart: true do
                div = file_field_tag :csv_file
                div = submit_tag :upload

- else
    .container
        .row
            .col-6  
                .float-right
                    = link_to admin_session_path do
                        = button_tag 'Login', class: 'btn btn-primary'
                h1 List of stock
                
        .row
            .col
                = form_tag products_path, method: :get do
                    = text_field_tag 'search', '', placeholder: 'Type something here',
                        class: 'form-control'
        br
        .row-mt-2
            .col
                table.table.table-bordered.table-striped
                    thead.thead-dark
                        tr
                            th Title
                            th Status
                            th Description
                            th Stock
                            th Category
                    tbody
                      - @products.each do |a|
                        tr
                            td.font-weight-bold = a.title
                            td.font-weight-light = a.status
                            td = a.description
                            td = a.stock
                            td = render a.categories

        .row
            .col-6
                = paginate @products

app/views/products/new.slim
h1 Add new stock

div = link_to products_path do
        = button_tag 'Back', class: 'btn btn-primary'
br
= render 'form', product: @product